name: CI

on:
  - pull_request
  - push

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-2019
        node_version:
          - 14
          - 16
        node_arch:
          - x64
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.node_arch }}
          check-latest: true

      - name: Install dependencies
        run: npm install

      - if: "!contains(matrix.os, 'windows')"
        name: Get nodeVersion for cache step
        id: get-node-version
        run: echo "NODE_VERSION=`node -e "console.log(require('./spec/config.json').nodeVersion)"`" > $GITHUB_OUTPUT

      - if: "!contains(matrix.os, 'windows')"
        name: Cache NodeJS source fixtures
        uses: actions/cache@v3
        with:
          path: spec/fixtures/node-source
          key: nodeVersion-${{ steps.get-node-version.outputs.NODE_VERSION }}

      - if: "!contains(matrix.os, 'windows')"
        name: Run tests 👩🏾‍💻
        run: ./bin/npm test

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
